# kinematics.yaml
#
# MoveIt2 运动学插件配置，定义使用的求解器（如KDL）及求解参数。

arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
